import React from 'react'
import Head from 'next/head'
import Navigation from '@/components/Navigation'
import MiniLanding from '@/components/MiniLanding'
import ReleasesContent from '@/components/ReleasesContent'
import Footer from '@/components/Footer'

import dbConnect from '@/lib/dbConnect'
import IllgodRelease from '@/models/IllgodRelease'


function Releases({releases, page, count}) {
    const lastPage = Math.ceil(count/30)

    //reverse releases array
    const releasesSort = releases.reverse()

    return (
        <>
            <Head>
                <title>Illgod</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Navigation />
                <MiniLanding header={'Releases'} />
                <ReleasesContent releases={releasesSort} />
                <Footer />
            </>
        </>
    )
}

export default Releases

export async function getServerSideProps({ query: {page = 1}}) {
    await dbConnect()

    const options = {
        page: page,
        limit: 30
    }

    const result = await IllgodRelease.paginate({}, options)
    //console.log(result)
    const releases = result.docs.map((doc) => {
        const release = doc.toObject()
        release._id = release._id.toString()
        release.date = release.date.toString()
        return release
    })

    return {
        props: {
            releases: releases,
            page: parseInt(result.page),
            count: parseInt(result.totalDocs)
        },
    }
}