import Head from 'next/head'
import Landing from '@/components/Landing'
import Navigation from '@/components/Navigation'
import AfterLanding from '@/components/AfterLanding'
import Footer from '@/components/Footer'

import { motion } from 'framer-motion'



export default function Home() {
  return (
    <>
      <Head>
        <title>Illgod</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        exit={{ opacity: 0 }}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
      >
        <Navigation />
        <Landing />
        <AfterLanding />
        <Footer />
      </motion.main>
    </>
  )
}
